# 
# Tracker Makefile
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperfwil
#
SOURCES =	tracker-B_Cu.gbl tracker-B_Mask.gbs \
		tracker-F_Cu.gtl tracker-F_Mask.gts  \
		tracker-Edge_Cuts.gbr \
		tracker.drl

tracker.zip:	$(SOURCES)
	zip tracker.zip $(SOURCES)


